### ISSUE TITLE
Way to register a new feed source

### ISSUE THREAD

**Issue by skreutzer** [csensemakers/lib-protocol-experiments#2]
A way is needed for people to register a new feed source.

Could be a simple form, or manually operating an e-mail address (as an interim solution).

This mechanism should include an approval process, so the operator of the mechanism somehow gets notified about a new submission or has to actively review new entries, check the source and approve it to be added to a list of known source feeds. This implies that the mechanism produces a list of known feed sources, some of which might be already approved and others withheld, as still under manual review. Goal here is to not automatically have any URL added to the feed sources list, but only these that appear "compatible".

**Comment by ronentk** [comment]
This sounds a lot like the Index in Murmurations. 
https://docs.murmurations.network/about/common-terms.html

One question is regarding permissions - for more decentralization the registering could be automatic for any source providing a valid data format.
Moderation could happen at the querying level (a node with spam data may be ignored). What do you think?

**Comment by skreutzer** [comment]
> This sounds a lot like the Index in Murmurations.

Yes, except the Murmurations Index tracks Murmurations Nodes (participants, maybe even technically running their implementation?), and the Nodes are limited to the profiles/schemas Murmurations currently supports (I think). As they don't support a profile/schema for books yet, I doubt there's a way to add Library JSON sources to the Murmurations Index somehow. Could also be that they don't want to take book data (because why, what for?).

With this GitHub Issue, it's just asking for a method/mechanism/way for people to notify us/others that there's a source feed that could be added to the list/"index". Here described as a generic mechanism, which does not need to make assumptions about what kind of format or "profile"/"scheme" the source is. It's actually just a tool that helps producing/gathering a list of URLs (so actually, rather than joining + complying Murmurations, it might be more related to other work with collecting links, social bookmarking, building link lists, except the URLs collected is now not for a human a human reader to directly consume, but a list to then be visited by a crawler/retriever, see GitHub Issue #1).

Also, this tool/mechanism could be used by various users for different purposes (to produce different lists, including lists of lists a crawler might traverse eventually). Here we only need a way for pointing people to a "thing"/"place" to add their source feeds.

I think the ideal design goal would be to allow humans to submit feed sources to a list that's compiled in a code-readable form.

**Comment by skreutzer** [comment]
here https://groupware-systems.org/data-federation/data-entry/pattern_create.php?id_template=5
