### ISSUE TITLE
Converter to split hierarchical JSON into a graph representation

### ISSUE THREAD

**Issue by skreutzer** [csensemakers/lib-protocol-experiments#4]
Build a converter which takes as input the hierarchical JSON format and splits it up into a graph representation of the same data.

It is important to split the format into nodes for:

- originator (let's take one of `.name` or `.url`)
- internal book list/container (let's take one of `name` or `url` in `.lists[]`)
- book (let's take one of `title` or `id` in `.lists[].books[]`)

The relationship between these should be represented as edges.

After conversion, the graph representation is equivalent to the tree/hierarchy of the JSON format as the graph only uses (unidirectional) 1:n relationships as expressed in the source. Basically, the source format was already a graph syntax, but splitting it up from strict hierarchy/tree as inherent in JSON syntax into a collection of nodes and edges will subsequently allow to make n:m relationships.

**Comment by ronentk** [comment]
By `source` you mean the entity (person/group) that creaed the bookmark?

Also, perhaps worth making each bookmark a node, as they have some specific data associated with them

![image](https://user-images.githubusercontent.com/1759025/211720144-caf3c2f8-6ab5-4df6-ad11-2068e9d7a761.png)
![image](https://user-images.githubusercontent.com/1759025/211720197-623cbc47-4c75-4883-8cea-1b31f85b0344.png)

From our Miro
https://miro.com/app/board/uXjVPCr9zD8=/

**Comment by skreutzer** [comment]
`source`: Yes, you're right, I should clarify and update above! Often I use "source" as in "resource" (as in ReST), "data source" (in the JSON format). For the node entity to split the source into, what about disambiguating it as "originator"? Until there's a better name for it, in order to not confuse terminology. Thanks for the excellent observation!

**Comment by skreutzer** [comment]
Granularity of what to split into: in the first post, I kind of omitted the question of what to do with several data fields ("attributes", "properties") that belong to the same entity/node, for initial simplification (just picking one field, ideally somewhat identifying for the node).

There would be the option to split all associated fields that belong to the same entity/node into their own separate nodes, and connect these to a "virtual" or ID node which groups these together. Might be useful if some of such data should not be duplicated, for a scenario where, let's say, a `Person` having a first/given name, and if that's made an extra node connected to the virtual parent node representing the natural person, then that allows to more easily compile/query for all persons with the same first/given name. Downside is more graph operations to get to a full (or sufficiently useful) record.

Other option is to just attach these "fields"/"attributes" at the node, be it some blob or other payload, which represents a 1:1 relation and not providing a mechanism to connect these values to other nodes, hence there might be some duplication. But this can also be intentional design, for example changing such a field/attribute should not affect and replicate to a whole number of other unrelated nodes, who only shared a field value for as long as it remained the same as the value they wanted to refer to.

Assumption is we'll find a solution later, or leave it open to implementers for how they want to go about it for now, as for a start we minimally conceptually need to somehow work with the main/primary entities we get from the source format.

**Comment by skreutzer** [comment]
Thanks a lot for sharing the Miro! Issues/proposals here somewhat map to the diagram in Miro, but not entirely, and too the Miro diagram tends to describe more the use case, application, activity, content, and the few Issues I created so far are more from a technical, functional, component perspective.

To me there seems to be no `Bookmark` per se in the Library JSON source format, are you proposing a GitHub Issue could be created to discuss what a bookmark might do and represent, and if not in the sources, that's data we or others produce and contribute?

**Comment by skreutzer** [comment]
So [this](https://github.com/csensemakers/lib-protocol-experiments/commit/6dbbc84a87fd28bf646e8ba10c041ecd37966162) is not a great way of doing it, but can serve as a first, simple solution. I can port to other programming languages, if anybody has the need.

Produces output like

```
node 1 "https://skreutzer.de"
node 2 "Books Read"
edge 2 1
node 3 "The New Media Reader"
edge 3 2
node 4 "Personal Knowledge – Towards a Post-Critical Philosophy"
edge 4 2
node 5 "Die Heilige Schrift – Aus dem Grundtext übersetzt"
edge 5 2
…
```

The notation/format of the output doesn't matter, I just made it up for illustration purposes - the "back-end"/output-generation can be adapted/rewritten to generate any graph-oriented format (I can make a version that supports your format needs, if you can't or don't want to make such a variant yourself). So this is some kind of format-converter/adapter. The method is more important than the particular implementation (as there can be many implementations, performing the same/similar function/conversion).

**Comment by ronentk** [comment]
> To me there seems to be no Bookmark per se in the Library JSON source format, are you proposing a GitHub Issue could be created to discuss what a bookmark might do and represent, and if not in the sources, that's data we or others produce and contribute?

Yes exactly! I opened #9 :)
